/* Copyright (C) 2014-2018 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2018-08-27
// KLL Emitter:        kiibohd
// KLL Version:        BETA 0.5c.f42eca6a53c84bcd093a0e12149789db4f14f98c - 2018-04-08 20:48:41 -0700
// KLL Git Changes:    None
// Compiler arguments:
//      /srv/KiiConf/controller/kll/kll
//    --kiibohd-debug
//    --config
//      /srv/KiiConf/controller/Scan/Devices/ISSILed/capabilities.kll
//      /srv/KiiConf/controller/Scan/Devices/MatrixARMPeriodic/capabilities.kll
//      /srv/KiiConf/controller/Macro/PartialMap/capabilities.kll
//      /srv/KiiConf/controller/Macro/PixelMap/capabilities.kll
//      /srv/KiiConf/controller/Output/HID-IO/capabilities.kll
//      /srv/KiiConf/controller/Output/USB/capabilities.kll
//      /srv/KiiConf/controller/Debug/latency/capabilities.kll
//    --base
//      /srv/KiiConf/controller/Scan/Infinity_60_LED/scancode_map.kll
//      /srv/KiiConf/controller/Scan/Infinity_60_LED/scancode_map.standard.kll
//    --default
//      /srv/KiiConf/controller/kll/layouts/stdFuncMap.kll
//      MD1.1-Standard-0.kll
//    --partial
//      /srv/KiiConf/controller/kll/layouts/stdFuncMap.kll
//      MD1.1-Standard-1.kll
//    --partial
//      /srv/KiiConf/controller/kll/layouts/stdFuncMap.kll
//      MD1.1-Standard-2.kll
//    --partial
//      /srv/KiiConf/controller/kll/layouts/stdFuncMap.kll
//      MD1.1-Standard-3.kll
//    --emitter
//      kiibohd
//    --def-template
//      /srv/KiiConf/controller/kll/templates/kiibohdDefs.h
//    --map-template
//      /srv/KiiConf/controller/kll/templates/kiibohdKeymap.h
//    --pixel-template
//      /srv/KiiConf/controller/kll/templates/kiibohdPixelmap.c
//    --def-output
//      kll_defs.h
//    --map-output
//      generatedKeymap.h
//    --pixel-output
//      generatedPixelmap.c
//    --preprocessor-tmp-path
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll
//
// - Configuration File -
//    ISSILedCapabilities
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll
//    MatrixARMPeriodicCapabilities
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll
//    PartialMapCapabilities
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Macro_PartialMap@['capabilities']_processed.kll
//    PixelMapCapabilities
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Macro_PixelMap@['capabilities']_processed.kll
//    HID-IOCapabilities
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Output_HID-IO@['capabilities']_processed.kll
//    USBCapabilities
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Output_USB@['capabilities']_processed.kll
//    latency
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Debug_latency@['capabilities']_processed.kll
// - Generic Files -
// - Base Layer -
//    Infinity 60% LED
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map']_processed.kll
//    Infinity 60% LED Standard
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map', 'standard']_processed.kll
// - Default Layer -
//    stdFuncMap
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll
//    MD1.1
//      /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/@['MD1', '1-Standard-0']_processed.kll
// - Partial Layers -
//    Layer 1
//     stdFuncMap
//       /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll
//     MD1.1
//       /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/@['MD1', '1-Standard-1']_processed.kll
//    Layer 2
//     stdFuncMap
//       /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll
//     MD1.1
//       /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/@['MD1', '1-Standard-2']_processed.kll
//    Layer 3
//     stdFuncMap
//       /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/_srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll
//     MD1.1
//       /srv/KiiConf/tmp/58fc8ac54458f977ea8db65490a5011115b840903db914/tmp_kll/@['MD1', '1-Standard-3']_processed.kll



#pragma once

// ----- Includes -----

// KLL Include
#include <kll.h>



// ----- Capabilities -----

// Capability function declarations
void LED_control_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerLatch_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerLock_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerRotate_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerShift_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerState_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_testThreadSafe_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_testThreadUnsafe_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_consCtrlSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_flashMode_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_kbdProtocolBoot_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_kbdProtocolNKRO_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_noneSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_sysCtrlSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_toggleKbdProtocol_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbCodeSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbMouseWheel_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbMouse_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_AnimationControl_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_AnimationIndex_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_Animation_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_Pixel_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );



// Indexed Capabilities Table
const Capability CapabilitiesList[] = {
	/* 0 ledControl */
	{ LED_control_capability, 2, CapabilityFeature_None },
	/* 1 layerLatch */
	{ Layer_layerLatch_capability, 2, CapabilityFeature_Safe },
	/* 2 layerLock */
	{ Layer_layerLock_capability, 2, CapabilityFeature_Safe },
	/* 3 layerRotate */
	{ Layer_layerRotate_capability, 1, CapabilityFeature_Safe },
	/* 4 layerShift */
	{ Layer_layerShift_capability, 2, CapabilityFeature_Safe },
	/* 5 layerState */
	{ Layer_layerState_capability, 3, CapabilityFeature_Safe },
	/* 6 testThreadSafe */
	{ Macro_testThreadSafe_capability, 0, CapabilityFeature_Safe },
	/* 7 testThreadUnsafe */
	{ Macro_testThreadUnsafe_capability, 0, CapabilityFeature_None },
	/* 8 consCtrlOut */
	{ Output_consCtrlSend_capability, 2, CapabilityFeature_Safe },
	/* 9 flashMode */
	{ Output_flashMode_capability, 0, CapabilityFeature_Safe },
	/* 10 kbdProtocolBoot */
	{ Output_kbdProtocolBoot_capability, 0, CapabilityFeature_None },
	/* 11 kbdProtocolNKRO */
	{ Output_kbdProtocolNKRO_capability, 0, CapabilityFeature_None },
	/* 12 noneOut */
	{ Output_noneSend_capability, 0, CapabilityFeature_Safe },
	/* 13 sysCtrlOut */
	{ Output_sysCtrlSend_capability, 1, CapabilityFeature_Safe },
	/* 14 toggleKbdProtocol */
	{ Output_toggleKbdProtocol_capability, 0, CapabilityFeature_None },
	/* 15 usbKeyOut */
	{ Output_usbCodeSend_capability, 1, CapabilityFeature_Safe },
	/* 16 mouseWheelOut */
	{ Output_usbMouseWheel_capability, 2, CapabilityFeature_None },
	/* 17 mouseOut */
	{ Output_usbMouse_capability, 6, CapabilityFeature_Safe },
	/* 18 animation_control */
	{ Pixel_AnimationControl_capability, 1, CapabilityFeature_None },
	/* 19 animationIndex */
	{ Pixel_AnimationIndex_capability, 2, CapabilityFeature_None },
	/* 20 animation */
	{ Pixel_Animation_capability, 7, CapabilityFeature_None },
	/* 21 pixel */
	{ Pixel_Pixel_capability, 0, CapabilityFeature_None },
};


// -- Result Macros

// Result Macro Guides
Guide_RM( 0 ) = { 1, 8, 111, 0, 0 }; // (HID(ConsCode)"CONSUMER_BRIGHTNESS_INCREMENT")
Guide_RM( 1 ) = { 1, 8, 112, 0, 0 }; // (HID(ConsCode)"CONSUMER_BRIGHTNESS_DECREMENT")
Guide_RM( 2 ) = { 1, 8, 181, 0, 0 }; // (HID(ConsCode)"CONSUMER_SCAN_NEXT_TRACK")
Guide_RM( 3 ) = { 1, 8, 205, 0, 0 }; // (HID(ConsCode)"CONSUMER_PAUSE_PLAY")
Guide_RM( 4 ) = { 1, 8, 226, 0, 0 }; // (HID(ConsCode)"CONSUMER_MUTE")
Guide_RM( 5 ) = { 1, 8, 233, 0, 0 }; // (HID(ConsCode)"CONSUMER_VOLUME_UP")
Guide_RM( 6 ) = { 1, 8, 234, 0, 0 }; // (HID(ConsCode)"CONSUMER_VOLUME_DOWN")
Guide_RM( 7 ) = { 1, 8, 146, 1, 0 }; // (HID(ConsCode)"AL_CALCULATOR")
Guide_RM( 8 ) = { 1, 8, 150, 1, 0 }; // (HID(ConsCode)"AL_INTERNET_BROWSER")
Guide_RM( 9 ) = { 1, 15, 0x00, 0 }; // (None)
Guide_RM( 10 ) = { 1, 15, KEY_A, 0 }; // (HID(USBCode)"KEY_A")
Guide_RM( 11 ) = { 1, 15, KEY_B, 0 }; // (HID(USBCode)"KEY_B")
Guide_RM( 12 ) = { 1, 15, KEY_C, 0 }; // (HID(USBCode)"KEY_C")
Guide_RM( 13 ) = { 1, 15, KEY_D, 0 }; // (HID(USBCode)"KEY_D")
Guide_RM( 14 ) = { 1, 15, KEY_E, 0 }; // (HID(USBCode)"KEY_E")
Guide_RM( 15 ) = { 1, 15, KEY_F, 0 }; // (HID(USBCode)"KEY_F")
Guide_RM( 16 ) = { 1, 15, KEY_G, 0 }; // (HID(USBCode)"KEY_G")
Guide_RM( 17 ) = { 1, 15, KEY_H, 0 }; // (HID(USBCode)"KEY_H")
Guide_RM( 18 ) = { 1, 15, KEY_I, 0 }; // (HID(USBCode)"KEY_I")
Guide_RM( 19 ) = { 1, 15, KEY_J, 0 }; // (HID(USBCode)"KEY_J")
Guide_RM( 20 ) = { 1, 15, KEY_K, 0 }; // (HID(USBCode)"KEY_K")
Guide_RM( 21 ) = { 1, 15, KEY_L, 0 }; // (HID(USBCode)"KEY_L")
Guide_RM( 22 ) = { 1, 15, KEY_M, 0 }; // (HID(USBCode)"KEY_M")
Guide_RM( 23 ) = { 1, 15, KEY_N, 0 }; // (HID(USBCode)"KEY_N")
Guide_RM( 24 ) = { 1, 15, KEY_O, 0 }; // (HID(USBCode)"KEY_O")
Guide_RM( 25 ) = { 1, 15, KEY_P, 0 }; // (HID(USBCode)"KEY_P")
Guide_RM( 26 ) = { 1, 15, KEY_Q, 0 }; // (HID(USBCode)"KEY_Q")
Guide_RM( 27 ) = { 1, 15, KEY_R, 0 }; // (HID(USBCode)"KEY_R")
Guide_RM( 28 ) = { 1, 15, KEY_S, 0 }; // (HID(USBCode)"KEY_S")
Guide_RM( 29 ) = { 1, 15, KEY_T, 0 }; // (HID(USBCode)"KEY_T")
Guide_RM( 30 ) = { 1, 15, KEY_U, 0 }; // (HID(USBCode)"KEY_U")
Guide_RM( 31 ) = { 1, 15, KEY_V, 0 }; // (HID(USBCode)"KEY_V")
Guide_RM( 32 ) = { 1, 15, KEY_W, 0 }; // (HID(USBCode)"KEY_W")
Guide_RM( 33 ) = { 1, 15, KEY_X, 0 }; // (HID(USBCode)"KEY_X")
Guide_RM( 34 ) = { 1, 15, KEY_Y, 0 }; // (HID(USBCode)"KEY_Y")
Guide_RM( 35 ) = { 1, 15, KEY_Z, 0 }; // (HID(USBCode)"KEY_Z")
Guide_RM( 36 ) = { 1, 15, KEY_1, 0 }; // (HID(USBCode)"KEY_1")
Guide_RM( 37 ) = { 1, 15, KEY_2, 0 }; // (HID(USBCode)"KEY_2")
Guide_RM( 38 ) = { 1, 15, KEY_3, 0 }; // (HID(USBCode)"KEY_3")
Guide_RM( 39 ) = { 1, 15, KEY_4, 0 }; // (HID(USBCode)"KEY_4")
Guide_RM( 40 ) = { 1, 15, KEY_5, 0 }; // (HID(USBCode)"KEY_5")
Guide_RM( 41 ) = { 1, 15, KEY_6, 0 }; // (HID(USBCode)"KEY_6")
Guide_RM( 42 ) = { 1, 15, KEY_7, 0 }; // (HID(USBCode)"KEY_7")
Guide_RM( 43 ) = { 1, 15, KEY_8, 0 }; // (HID(USBCode)"KEY_8")
Guide_RM( 44 ) = { 1, 15, KEY_9, 0 }; // (HID(USBCode)"KEY_9")
Guide_RM( 45 ) = { 1, 15, KEY_0, 0 }; // (HID(USBCode)"KEY_0")
Guide_RM( 46 ) = { 1, 15, KEY_ENTER, 0 }; // (HID(USBCode)"KEY_ENTER")
Guide_RM( 47 ) = { 1, 15, KEY_ESC, 0 }; // (HID(USBCode)"KEY_ESC")
Guide_RM( 48 ) = { 1, 15, KEY_BACKSPACE, 0 }; // (HID(USBCode)"KEY_BACKSPACE")
Guide_RM( 49 ) = { 1, 15, KEY_TAB, 0 }; // (HID(USBCode)"KEY_TAB")
Guide_RM( 50 ) = { 1, 15, KEY_SPACE, 0 }; // (HID(USBCode)"KEY_SPACE")
Guide_RM( 51 ) = { 1, 15, KEY_MINUS, 0 }; // (HID(USBCode)"KEY_MINUS")
Guide_RM( 52 ) = { 1, 15, KEY_EQUAL, 0 }; // (HID(USBCode)"KEY_EQUAL")
Guide_RM( 53 ) = { 1, 15, KEY_LEFT_BRACKET, 0 }; // (HID(USBCode)"KEY_LEFT_BRACKET")
Guide_RM( 54 ) = { 1, 15, KEY_RIGHT_BRACKET, 0 }; // (HID(USBCode)"KEY_RIGHT_BRACKET")
Guide_RM( 55 ) = { 1, 15, KEY_BACKSLASH, 0 }; // (HID(USBCode)"KEY_BACKSLASH")
Guide_RM( 56 ) = { 1, 15, KEY_SEMICOLON, 0 }; // (HID(USBCode)"KEY_SEMICOLON")
Guide_RM( 57 ) = { 1, 15, KEY_QUOTE, 0 }; // (HID(USBCode)"KEY_QUOTE")
Guide_RM( 58 ) = { 1, 15, KEY_BACKTICK, 0 }; // (HID(USBCode)"KEY_BACKTICK")
Guide_RM( 59 ) = { 1, 15, KEY_COMMA, 0 }; // (HID(USBCode)"KEY_COMMA")
Guide_RM( 60 ) = { 1, 15, KEY_PERIOD, 0 }; // (HID(USBCode)"KEY_PERIOD")
Guide_RM( 61 ) = { 1, 15, KEY_SLASH, 0 }; // (HID(USBCode)"KEY_SLASH")
Guide_RM( 62 ) = { 1, 15, KEY_F1, 0 }; // (HID(USBCode)"KEY_F1")
Guide_RM( 63 ) = { 1, 15, KEY_F2, 0 }; // (HID(USBCode)"KEY_F2")
Guide_RM( 64 ) = { 1, 15, KEY_F3, 0 }; // (HID(USBCode)"KEY_F3")
Guide_RM( 65 ) = { 1, 15, KEY_F4, 0 }; // (HID(USBCode)"KEY_F4")
Guide_RM( 66 ) = { 1, 15, KEY_F5, 0 }; // (HID(USBCode)"KEY_F5")
Guide_RM( 67 ) = { 1, 15, KEY_F6, 0 }; // (HID(USBCode)"KEY_F6")
Guide_RM( 68 ) = { 1, 15, KEY_F7, 0 }; // (HID(USBCode)"KEY_F7")
Guide_RM( 69 ) = { 1, 15, KEY_F8, 0 }; // (HID(USBCode)"KEY_F8")
Guide_RM( 70 ) = { 1, 15, KEY_F9, 0 }; // (HID(USBCode)"KEY_F9")
Guide_RM( 71 ) = { 1, 15, KEY_F10, 0 }; // (HID(USBCode)"KEY_F10")
Guide_RM( 72 ) = { 1, 15, KEY_F11, 0 }; // (HID(USBCode)"KEY_F11")
Guide_RM( 73 ) = { 1, 15, KEY_F12, 0 }; // (HID(USBCode)"KEY_F12")
Guide_RM( 74 ) = { 1, 15, KEY_SCROLL_LOCK, 0 }; // (HID(USBCode)"KEY_SCROLL_LOCK")
Guide_RM( 75 ) = { 1, 15, KEY_PAUSE, 0 }; // (HID(USBCode)"KEY_PAUSE")
Guide_RM( 76 ) = { 1, 15, KEY_INSERT, 0 }; // (HID(USBCode)"KEY_INSERT")
Guide_RM( 77 ) = { 1, 15, KEY_HOME, 0 }; // (HID(USBCode)"KEY_HOME")
Guide_RM( 78 ) = { 1, 15, KEY_PAGE_UP, 0 }; // (HID(USBCode)"KEY_PAGE_UP")
Guide_RM( 79 ) = { 1, 15, KEY_DELETE, 0 }; // (HID(USBCode)"KEY_DELETE")
Guide_RM( 80 ) = { 1, 15, KEY_END, 0 }; // (HID(USBCode)"KEY_END")
Guide_RM( 81 ) = { 1, 15, KEY_PAGE_DOWN, 0 }; // (HID(USBCode)"KEY_PAGE_DOWN")
Guide_RM( 82 ) = { 1, 15, KEY_RIGHT, 0 }; // (HID(USBCode)"KEY_RIGHT")
Guide_RM( 83 ) = { 1, 15, KEY_LEFT, 0 }; // (HID(USBCode)"KEY_LEFT")
Guide_RM( 84 ) = { 1, 15, KEY_DOWN, 0 }; // (HID(USBCode)"KEY_DOWN")
Guide_RM( 85 ) = { 1, 15, KEY_UP, 0 }; // (HID(USBCode)"KEY_UP")
Guide_RM( 86 ) = { 1, 15, KEY_APP, 0 }; // (HID(USBCode)"KEY_APP")
Guide_RM( 87 ) = { 1, 15, KEY_MENU, 0 }; // (HID(USBCode)"KEY_MENU")
Guide_RM( 88 ) = { 1, 15, KEY_LCTRL, 0 }; // (HID(USBCode)"KEY_LCTRL")
Guide_RM( 89 ) = { 1, 15, KEY_LSHIFT, 0 }; // (HID(USBCode)"KEY_LSHIFT")
Guide_RM( 90 ) = { 1, 15, KEY_LALT, 0 }; // (HID(USBCode)"KEY_LALT")
Guide_RM( 91 ) = { 1, 15, KEY_LGUI, 0 }; // (HID(USBCode)"KEY_LGUI")
Guide_RM( 92 ) = { 1, 15, KEY_RCTRL, 0 }; // (HID(USBCode)"KEY_RCTRL")
Guide_RM( 93 ) = { 1, 15, KEY_RSHIFT, 0 }; // (HID(USBCode)"KEY_RSHIFT")
Guide_RM( 94 ) = { 1, 15, KEY_RALT, 0 }; // (HID(USBCode)"KEY_RALT")
Guide_RM( 95 ) = { 1, 15, KEY_RGUI, 0 }; // (HID(USBCode)"KEY_RGUI")
Guide_RM( 96 ) = { 1, 9, 0 }; // (flashMode())
Guide_RM( 97 ) = { 1, 1, 3, 0, 0 }; // (layerLatch(3))
Guide_RM( 98 ) = { 1, 4, 1, 0, 0 }; // (layerShift(1))
Guide_RM( 99 ) = { 1, 4, 2, 0, 0 }; // (layerShift(2))
Guide_RM( 100 ) = { 1, 4, 3, 0, 0 }; // (layerShift(3))
Guide_RM( 101 ) = { 1, 4, 4, 0, 0 }; // (layerShift(4))
Guide_RM( 102 ) = { 1, 0, 0, 15, 0 }; // (ledControl(0,15))
Guide_RM( 103 ) = { 1, 0, 1, 15, 0 }; // (ledControl(1,15))
Guide_RM( 104 ) = { 1, 0, 3, 0, 0 }; // (ledControl(3,0))


// -- Result Macro List

// Indexed Table of Result Macros
const ResultMacro ResultMacroList[] = {
	Define_RM( 0 ), // (HID(ConsCode)"CONSUMER_BRIGHTNESS_INCREMENT")
	Define_RM( 1 ), // (HID(ConsCode)"CONSUMER_BRIGHTNESS_DECREMENT")
	Define_RM( 2 ), // (HID(ConsCode)"CONSUMER_SCAN_NEXT_TRACK")
	Define_RM( 3 ), // (HID(ConsCode)"CONSUMER_PAUSE_PLAY")
	Define_RM( 4 ), // (HID(ConsCode)"CONSUMER_MUTE")
	Define_RM( 5 ), // (HID(ConsCode)"CONSUMER_VOLUME_UP")
	Define_RM( 6 ), // (HID(ConsCode)"CONSUMER_VOLUME_DOWN")
	Define_RM( 7 ), // (HID(ConsCode)"AL_CALCULATOR")
	Define_RM( 8 ), // (HID(ConsCode)"AL_INTERNET_BROWSER")
	Define_RM( 9 ), // (None)
	Define_RM( 10 ), // (HID(USBCode)"KEY_A")
	Define_RM( 11 ), // (HID(USBCode)"KEY_B")
	Define_RM( 12 ), // (HID(USBCode)"KEY_C")
	Define_RM( 13 ), // (HID(USBCode)"KEY_D")
	Define_RM( 14 ), // (HID(USBCode)"KEY_E")
	Define_RM( 15 ), // (HID(USBCode)"KEY_F")
	Define_RM( 16 ), // (HID(USBCode)"KEY_G")
	Define_RM( 17 ), // (HID(USBCode)"KEY_H")
	Define_RM( 18 ), // (HID(USBCode)"KEY_I")
	Define_RM( 19 ), // (HID(USBCode)"KEY_J")
	Define_RM( 20 ), // (HID(USBCode)"KEY_K")
	Define_RM( 21 ), // (HID(USBCode)"KEY_L")
	Define_RM( 22 ), // (HID(USBCode)"KEY_M")
	Define_RM( 23 ), // (HID(USBCode)"KEY_N")
	Define_RM( 24 ), // (HID(USBCode)"KEY_O")
	Define_RM( 25 ), // (HID(USBCode)"KEY_P")
	Define_RM( 26 ), // (HID(USBCode)"KEY_Q")
	Define_RM( 27 ), // (HID(USBCode)"KEY_R")
	Define_RM( 28 ), // (HID(USBCode)"KEY_S")
	Define_RM( 29 ), // (HID(USBCode)"KEY_T")
	Define_RM( 30 ), // (HID(USBCode)"KEY_U")
	Define_RM( 31 ), // (HID(USBCode)"KEY_V")
	Define_RM( 32 ), // (HID(USBCode)"KEY_W")
	Define_RM( 33 ), // (HID(USBCode)"KEY_X")
	Define_RM( 34 ), // (HID(USBCode)"KEY_Y")
	Define_RM( 35 ), // (HID(USBCode)"KEY_Z")
	Define_RM( 36 ), // (HID(USBCode)"KEY_1")
	Define_RM( 37 ), // (HID(USBCode)"KEY_2")
	Define_RM( 38 ), // (HID(USBCode)"KEY_3")
	Define_RM( 39 ), // (HID(USBCode)"KEY_4")
	Define_RM( 40 ), // (HID(USBCode)"KEY_5")
	Define_RM( 41 ), // (HID(USBCode)"KEY_6")
	Define_RM( 42 ), // (HID(USBCode)"KEY_7")
	Define_RM( 43 ), // (HID(USBCode)"KEY_8")
	Define_RM( 44 ), // (HID(USBCode)"KEY_9")
	Define_RM( 45 ), // (HID(USBCode)"KEY_0")
	Define_RM( 46 ), // (HID(USBCode)"KEY_ENTER")
	Define_RM( 47 ), // (HID(USBCode)"KEY_ESC")
	Define_RM( 48 ), // (HID(USBCode)"KEY_BACKSPACE")
	Define_RM( 49 ), // (HID(USBCode)"KEY_TAB")
	Define_RM( 50 ), // (HID(USBCode)"KEY_SPACE")
	Define_RM( 51 ), // (HID(USBCode)"KEY_MINUS")
	Define_RM( 52 ), // (HID(USBCode)"KEY_EQUAL")
	Define_RM( 53 ), // (HID(USBCode)"KEY_LEFT_BRACKET")
	Define_RM( 54 ), // (HID(USBCode)"KEY_RIGHT_BRACKET")
	Define_RM( 55 ), // (HID(USBCode)"KEY_BACKSLASH")
	Define_RM( 56 ), // (HID(USBCode)"KEY_SEMICOLON")
	Define_RM( 57 ), // (HID(USBCode)"KEY_QUOTE")
	Define_RM( 58 ), // (HID(USBCode)"KEY_BACKTICK")
	Define_RM( 59 ), // (HID(USBCode)"KEY_COMMA")
	Define_RM( 60 ), // (HID(USBCode)"KEY_PERIOD")
	Define_RM( 61 ), // (HID(USBCode)"KEY_SLASH")
	Define_RM( 62 ), // (HID(USBCode)"KEY_F1")
	Define_RM( 63 ), // (HID(USBCode)"KEY_F2")
	Define_RM( 64 ), // (HID(USBCode)"KEY_F3")
	Define_RM( 65 ), // (HID(USBCode)"KEY_F4")
	Define_RM( 66 ), // (HID(USBCode)"KEY_F5")
	Define_RM( 67 ), // (HID(USBCode)"KEY_F6")
	Define_RM( 68 ), // (HID(USBCode)"KEY_F7")
	Define_RM( 69 ), // (HID(USBCode)"KEY_F8")
	Define_RM( 70 ), // (HID(USBCode)"KEY_F9")
	Define_RM( 71 ), // (HID(USBCode)"KEY_F10")
	Define_RM( 72 ), // (HID(USBCode)"KEY_F11")
	Define_RM( 73 ), // (HID(USBCode)"KEY_F12")
	Define_RM( 74 ), // (HID(USBCode)"KEY_SCROLL_LOCK")
	Define_RM( 75 ), // (HID(USBCode)"KEY_PAUSE")
	Define_RM( 76 ), // (HID(USBCode)"KEY_INSERT")
	Define_RM( 77 ), // (HID(USBCode)"KEY_HOME")
	Define_RM( 78 ), // (HID(USBCode)"KEY_PAGE_UP")
	Define_RM( 79 ), // (HID(USBCode)"KEY_DELETE")
	Define_RM( 80 ), // (HID(USBCode)"KEY_END")
	Define_RM( 81 ), // (HID(USBCode)"KEY_PAGE_DOWN")
	Define_RM( 82 ), // (HID(USBCode)"KEY_RIGHT")
	Define_RM( 83 ), // (HID(USBCode)"KEY_LEFT")
	Define_RM( 84 ), // (HID(USBCode)"KEY_DOWN")
	Define_RM( 85 ), // (HID(USBCode)"KEY_UP")
	Define_RM( 86 ), // (HID(USBCode)"KEY_APP")
	Define_RM( 87 ), // (HID(USBCode)"KEY_MENU")
	Define_RM( 88 ), // (HID(USBCode)"KEY_LCTRL")
	Define_RM( 89 ), // (HID(USBCode)"KEY_LSHIFT")
	Define_RM( 90 ), // (HID(USBCode)"KEY_LALT")
	Define_RM( 91 ), // (HID(USBCode)"KEY_LGUI")
	Define_RM( 92 ), // (HID(USBCode)"KEY_RCTRL")
	Define_RM( 93 ), // (HID(USBCode)"KEY_RSHIFT")
	Define_RM( 94 ), // (HID(USBCode)"KEY_RALT")
	Define_RM( 95 ), // (HID(USBCode)"KEY_RGUI")
	Define_RM( 96 ), // (flashMode())
	Define_RM( 97 ), // (layerLatch(3))
	Define_RM( 98 ), // (layerShift(1))
	Define_RM( 99 ), // (layerShift(2))
	Define_RM( 100 ), // (layerShift(3))
	Define_RM( 101 ), // (layerShift(4))
	Define_RM( 102 ), // (ledControl(0,15))
	Define_RM( 103 ), // (ledControl(1,15))
	Define_RM( 104 ), // (ledControl(3,0))
};


// -- Trigger Macros

// Trigger Macro Guides
Guide_TM( 0 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x01, 0 }; // (S001)
Guide_TM( 1 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x02, 0 }; // (S002)
Guide_TM( 2 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x03, 0 }; // (S003)
Guide_TM( 3 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x04, 0 }; // (S004)
Guide_TM( 4 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x05, 0 }; // (S005)
Guide_TM( 5 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x06, 0 }; // (S006)
Guide_TM( 6 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x07, 0 }; // (S007)
Guide_TM( 7 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x08, 0 }; // (S008)
Guide_TM( 8 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x09, 0 }; // (S009)
Guide_TM( 9 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0A, 0 }; // (S010)
Guide_TM( 10 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0B, 0 }; // (S011)
Guide_TM( 11 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0C, 0 }; // (S012)
Guide_TM( 12 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0D, 0 }; // (S013)
Guide_TM( 13 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0E, 0 }; // (S014)
Guide_TM( 14 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0F, 0 }; // (S015)
Guide_TM( 15 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x10, 0 }; // (S016)
Guide_TM( 16 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x11, 0 }; // (S017)
Guide_TM( 17 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x12, 0 }; // (S018)
Guide_TM( 18 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x13, 0 }; // (S019)
Guide_TM( 19 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x14, 0 }; // (S020)
Guide_TM( 20 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x15, 0 }; // (S021)
Guide_TM( 21 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x16, 0 }; // (S022)
Guide_TM( 22 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x17, 0 }; // (S023)
Guide_TM( 23 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x18, 0 }; // (S024)
Guide_TM( 24 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x19, 0 }; // (S025)
Guide_TM( 25 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1A, 0 }; // (S026)
Guide_TM( 26 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1B, 0 }; // (S027)
Guide_TM( 27 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1C, 0 }; // (S028)
Guide_TM( 28 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1D, 0 }; // (S029)
Guide_TM( 29 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1E, 0 }; // (S030)
Guide_TM( 30 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1F, 0 }; // (S031)
Guide_TM( 31 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x20, 0 }; // (S032)
Guide_TM( 32 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x21, 0 }; // (S033)
Guide_TM( 33 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x22, 0 }; // (S034)
Guide_TM( 34 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x23, 0 }; // (S035)
Guide_TM( 35 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x24, 0 }; // (S036)
Guide_TM( 36 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x25, 0 }; // (S037)
Guide_TM( 37 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x26, 0 }; // (S038)
Guide_TM( 38 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x27, 0 }; // (S039)
Guide_TM( 39 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x28, 0 }; // (S040)
Guide_TM( 40 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x29, 0 }; // (S041)
Guide_TM( 41 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2A, 0 }; // (S042)
Guide_TM( 42 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2B, 0 }; // (S043)
Guide_TM( 43 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2C, 0 }; // (S044)
Guide_TM( 44 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2D, 0 }; // (S045)
Guide_TM( 45 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2E, 0 }; // (S046)
Guide_TM( 46 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2F, 0 }; // (S047)
Guide_TM( 47 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x30, 0 }; // (S048)
Guide_TM( 48 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x31, 0 }; // (S049)
Guide_TM( 49 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x32, 0 }; // (S050)
Guide_TM( 50 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x33, 0 }; // (S051)
Guide_TM( 51 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x34, 0 }; // (S052)
Guide_TM( 52 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x35, 0 }; // (S053)
Guide_TM( 53 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x36, 0 }; // (S054)
Guide_TM( 54 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x37, 0 }; // (S055)
Guide_TM( 55 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x38, 0 }; // (S056)
Guide_TM( 56 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x39, 0 }; // (S057)
Guide_TM( 57 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3A, 0 }; // (S058)
Guide_TM( 58 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3B, 0 }; // (S059)
Guide_TM( 59 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3C, 0 }; // (S060)
Guide_TM( 60 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3D, 0 }; // (S061)
Guide_TM( 61 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3E, 0 }; // (S062)
Guide_TM( 62 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3F, 0 }; // (S063)


// -- Trigger Macro List

// Indexed Table of Trigger Macros
const TriggerMacro TriggerMacroList[] = {
	/* 0 */ Define_TM( 0, 48 ), // (S001) : (HID(USBCode)"KEY_BACKSPACE");
	/* 1 */ Define_TM( 0, 47 ), // (S001) : (HID(USBCode)"KEY_ESC");
	/* 2 */ Define_TM( 1, 36 ), // (S002) : (HID(USBCode)"KEY_1");
	/* 3 */ Define_TM( 1, 62 ), // (S002) : (HID(USBCode)"KEY_F1");
	/* 4 */ Define_TM( 2, 37 ), // (S003) : (HID(USBCode)"KEY_2");
	/* 5 */ Define_TM( 2, 63 ), // (S003) : (HID(USBCode)"KEY_F2");
	/* 6 */ Define_TM( 3, 38 ), // (S004) : (HID(USBCode)"KEY_3");
	/* 7 */ Define_TM( 3, 64 ), // (S004) : (HID(USBCode)"KEY_F3");
	/* 8 */ Define_TM( 4, 39 ), // (S005) : (HID(USBCode)"KEY_4");
	/* 9 */ Define_TM( 4, 65 ), // (S005) : (HID(USBCode)"KEY_F4");
	/* 10 */ Define_TM( 5, 40 ), // (S006) : (HID(USBCode)"KEY_5");
	/* 11 */ Define_TM( 5, 66 ), // (S006) : (HID(USBCode)"KEY_F5");
	/* 12 */ Define_TM( 6, 67 ), // (S007) : (HID(USBCode)"KEY_F6");
	/* 13 */ Define_TM( 6, 41 ), // (S007) : (HID(USBCode)"KEY_6");
	/* 14 */ Define_TM( 7, 68 ), // (S008) : (HID(USBCode)"KEY_F7");
	/* 15 */ Define_TM( 7, 42 ), // (S008) : (HID(USBCode)"KEY_7");
	/* 16 */ Define_TM( 8, 43 ), // (S009) : (HID(USBCode)"KEY_8");
	/* 17 */ Define_TM( 8, 69 ), // (S009) : (HID(USBCode)"KEY_F8");
	/* 18 */ Define_TM( 9, 70 ), // (S010) : (HID(USBCode)"KEY_F9");
	/* 19 */ Define_TM( 9, 44 ), // (S010) : (HID(USBCode)"KEY_9");
	/* 20 */ Define_TM( 10, 71 ), // (S011) : (HID(USBCode)"KEY_F10");
	/* 21 */ Define_TM( 10, 45 ), // (S011) : (HID(USBCode)"KEY_0");
	/* 22 */ Define_TM( 11, 72 ), // (S012) : (HID(USBCode)"KEY_F11");
	/* 23 */ Define_TM( 11, 51 ), // (S012) : (HID(USBCode)"KEY_MINUS");
	/* 24 */ Define_TM( 12, 73 ), // (S013) : (HID(USBCode)"KEY_F12");
	/* 25 */ Define_TM( 12, 52 ), // (S013) : (HID(USBCode)"KEY_EQUAL");
	/* 26 */ Define_TM( 13, 76 ), // (S014) : (HID(USBCode)"KEY_INSERT");
	/* 27 */ Define_TM( 13, 55 ), // (S014) : (HID(USBCode)"KEY_BACKSLASH");
	/* 28 */ Define_TM( 14, 79 ), // (S015) : (HID(USBCode)"KEY_DELETE");
	/* 29 */ Define_TM( 14, 48 ), // (S015) : (HID(USBCode)"KEY_BACKSPACE");
	/* 30 */ Define_TM( 15, 97 ), // (S016) : (layerLatch(3));
	/* 31 */ Define_TM( 15, 49 ), // (S016) : (HID(USBCode)"KEY_TAB");
	/* 32 */ Define_TM( 16, 26 ), // (S017) : (HID(USBCode)"KEY_Q");
	/* 33 */ Define_TM( 16, 66 ), // (S017) : (HID(USBCode)"KEY_F5");
	/* 34 */ Define_TM( 16, 46 ), // (S017) : (HID(USBCode)"KEY_ENTER");
	/* 35 */ Define_TM( 17, 67 ), // (S018) : (HID(USBCode)"KEY_F6");
	/* 36 */ Define_TM( 17, 32 ), // (S018) : (HID(USBCode)"KEY_W");
	/* 37 */ Define_TM( 17, 85 ), // (S018) : (HID(USBCode)"KEY_UP");
	/* 38 */ Define_TM( 17, 96 ), // (S018) : (flashMode());
	/* 39 */ Define_TM( 18, 80 ), // (S019) : (HID(USBCode)"KEY_END");
	/* 40 */ Define_TM( 18, 68 ), // (S019) : (HID(USBCode)"KEY_F7");
	/* 41 */ Define_TM( 18, 14 ), // (S019) : (HID(USBCode)"KEY_E");
	/* 42 */ Define_TM( 19, 27 ), // (S020) : (HID(USBCode)"KEY_R");
	/* 43 */ Define_TM( 19, 69 ), // (S020) : (HID(USBCode)"KEY_F8");
	/* 44 */ Define_TM( 19, 78 ), // (S020) : (HID(USBCode)"KEY_PAGE_UP");
	/* 45 */ Define_TM( 20, 29 ), // (S021) : (HID(USBCode)"KEY_T");
	/* 46 */ Define_TM( 21, 34 ), // (S022) : (HID(USBCode)"KEY_Y");
	/* 47 */ Define_TM( 22, 30 ), // (S023) : (HID(USBCode)"KEY_U");
	/* 48 */ Define_TM( 23, 85 ), // (S024) : (HID(USBCode)"KEY_UP");
	/* 49 */ Define_TM( 23, 18 ), // (S024) : (HID(USBCode)"KEY_I");
	/* 50 */ Define_TM( 24, 74 ), // (S025) : (HID(USBCode)"KEY_SCROLL_LOCK");
	/* 51 */ Define_TM( 24, 24 ), // (S025) : (HID(USBCode)"KEY_O");
	/* 52 */ Define_TM( 25, 75 ), // (S026) : (HID(USBCode)"KEY_PAUSE");
	/* 53 */ Define_TM( 25, 25 ), // (S026) : (HID(USBCode)"KEY_P");
	/* 54 */ Define_TM( 26, 80 ), // (S027) : (HID(USBCode)"KEY_END");
	/* 55 */ Define_TM( 26, 53 ), // (S027) : (HID(USBCode)"KEY_LEFT_BRACKET");
	/* 56 */ Define_TM( 27, 54 ), // (S028) : (HID(USBCode)"KEY_RIGHT_BRACKET");
	/* 57 */ Define_TM( 27, 78 ), // (S028) : (HID(USBCode)"KEY_PAGE_UP");
	/* 58 */ Define_TM( 28, 58 ), // (S029) : (HID(USBCode)"KEY_BACKTICK");
	/* 59 */ Define_TM( 28, 79 ), // (S029) : (HID(USBCode)"KEY_DELETE");
	/* 60 */ Define_TM( 29, 98 ), // (S030) : (layerShift(1));
	/* 61 */ Define_TM( 29, 9 ), // (S030) : (None);
	/* 62 */ Define_TM( 30, 10 ), // (S031) : (HID(USBCode)"KEY_A");
	/* 63 */ Define_TM( 30, 102 ), // (S031) : (ledControl(0,15));
	/* 64 */ Define_TM( 30, 83 ), // (S031) : (HID(USBCode)"KEY_LEFT");
	/* 65 */ Define_TM( 30, 70 ), // (S031) : (HID(USBCode)"KEY_F9");
	/* 66 */ Define_TM( 31, 84 ), // (S032) : (HID(USBCode)"KEY_DOWN");
	/* 67 */ Define_TM( 31, 28 ), // (S032) : (HID(USBCode)"KEY_S");
	/* 68 */ Define_TM( 31, 71 ), // (S032) : (HID(USBCode)"KEY_F10");
	/* 69 */ Define_TM( 31, 103 ), // (S032) : (ledControl(1,15));
	/* 70 */ Define_TM( 32, 13 ), // (S033) : (HID(USBCode)"KEY_D");
	/* 71 */ Define_TM( 32, 72 ), // (S033) : (HID(USBCode)"KEY_F11");
	/* 72 */ Define_TM( 32, 82 ), // (S033) : (HID(USBCode)"KEY_RIGHT");
	/* 73 */ Define_TM( 32, 104 ), // (S033) : (ledControl(3,0));
	/* 74 */ Define_TM( 33, 15 ), // (S034) : (HID(USBCode)"KEY_F");
	/* 75 */ Define_TM( 33, 73 ), // (S034) : (HID(USBCode)"KEY_F12");
	/* 76 */ Define_TM( 33, 81 ), // (S034) : (HID(USBCode)"KEY_PAGE_DOWN");
	/* 77 */ Define_TM( 34, 16 ), // (S035) : (HID(USBCode)"KEY_G");
	/* 78 */ Define_TM( 35, 17 ), // (S036) : (HID(USBCode)"KEY_H");
	/* 79 */ Define_TM( 36, 19 ), // (S037) : (HID(USBCode)"KEY_J");
	/* 80 */ Define_TM( 36, 83 ), // (S037) : (HID(USBCode)"KEY_LEFT");
	/* 81 */ Define_TM( 37, 20 ), // (S038) : (HID(USBCode)"KEY_K");
	/* 82 */ Define_TM( 37, 84 ), // (S038) : (HID(USBCode)"KEY_DOWN");
	/* 83 */ Define_TM( 38, 21 ), // (S039) : (HID(USBCode)"KEY_L");
	/* 84 */ Define_TM( 38, 82 ), // (S039) : (HID(USBCode)"KEY_RIGHT");
	/* 85 */ Define_TM( 39, 77 ), // (S040) : (HID(USBCode)"KEY_HOME");
	/* 86 */ Define_TM( 39, 56 ), // (S040) : (HID(USBCode)"KEY_SEMICOLON");
	/* 87 */ Define_TM( 40, 81 ), // (S041) : (HID(USBCode)"KEY_PAGE_DOWN");
	/* 88 */ Define_TM( 40, 57 ), // (S041) : (HID(USBCode)"KEY_QUOTE");
	/* 89 */ Define_TM( 41, 46 ), // (S042) : (HID(USBCode)"KEY_ENTER");
	/* 90 */ Define_TM( 42, 99 ), // (S043) : (layerShift(2));
	/* 91 */ Define_TM( 42, 89 ), // (S043) : (HID(USBCode)"KEY_LSHIFT");
	/* 92 */ Define_TM( 43, 35 ), // (S044) : (HID(USBCode)"KEY_Z");
	/* 93 */ Define_TM( 43, 4 ), // (S044) : (HID(ConsCode)"CONSUMER_MUTE");
	/* 94 */ Define_TM( 44, 33 ), // (S045) : (HID(USBCode)"KEY_X");
	/* 95 */ Define_TM( 44, 6 ), // (S045) : (HID(ConsCode)"CONSUMER_VOLUME_DOWN");
	/* 96 */ Define_TM( 45, 5 ), // (S046) : (HID(ConsCode)"CONSUMER_VOLUME_UP");
	/* 97 */ Define_TM( 45, 12 ), // (S046) : (HID(USBCode)"KEY_C");
	/* 98 */ Define_TM( 46, 31 ), // (S047) : (HID(USBCode)"KEY_V");
	/* 99 */ Define_TM( 46, 3 ), // (S047) : (HID(ConsCode)"CONSUMER_PAUSE_PLAY");
	/* 100 */ Define_TM( 47, 11 ), // (S048) : (HID(USBCode)"KEY_B");
	/* 101 */ Define_TM( 47, 2 ), // (S048) : (HID(ConsCode)"CONSUMER_SCAN_NEXT_TRACK");
	/* 102 */ Define_TM( 48, 23 ), // (S049) : (HID(USBCode)"KEY_N");
	/* 103 */ Define_TM( 48, 7 ), // (S049) : (HID(ConsCode)"AL_CALCULATOR");
	/* 104 */ Define_TM( 49, 8 ), // (S050) : (HID(ConsCode)"AL_INTERNET_BROWSER");
	/* 105 */ Define_TM( 49, 22 ), // (S050) : (HID(USBCode)"KEY_M");
	/* 106 */ Define_TM( 50, 80 ), // (S051) : (HID(USBCode)"KEY_END");
	/* 107 */ Define_TM( 50, 59 ), // (S051) : (HID(USBCode)"KEY_COMMA");
	/* 108 */ Define_TM( 51, 1 ), // (S052) : (HID(ConsCode)"CONSUMER_BRIGHTNESS_DECREMENT");
	/* 109 */ Define_TM( 51, 60 ), // (S052) : (HID(USBCode)"KEY_PERIOD");
	/* 110 */ Define_TM( 52, 0 ), // (S053) : (HID(ConsCode)"CONSUMER_BRIGHTNESS_INCREMENT");
	/* 111 */ Define_TM( 52, 61 ), // (S053) : (HID(USBCode)"KEY_SLASH");
	/* 112 */ Define_TM( 53, 93 ), // (S054) : (HID(USBCode)"KEY_RSHIFT");
	/* 113 */ Define_TM( 54, 99 ), // (S055) : (layerShift(2));
	/* 114 */ Define_TM( 54, 98 ), // (S055) : (layerShift(1));
	/* 115 */ Define_TM( 54, 100 ), // (S055) : (layerShift(3));
	/* 116 */ Define_TM( 55, 46 ), // (S056) : (HID(USBCode)"KEY_ENTER");
	/* 117 */ Define_TM( 55, 88 ), // (S056) : (HID(USBCode)"KEY_LCTRL");
	/* 118 */ Define_TM( 56, 90 ), // (S057) : (HID(USBCode)"KEY_LALT");
	/* 119 */ Define_TM( 57, 91 ), // (S058) : (HID(USBCode)"KEY_LGUI");
	/* 120 */ Define_TM( 58, 3 ), // (S059) : (HID(ConsCode)"CONSUMER_PAUSE_PLAY");
	/* 121 */ Define_TM( 58, 50 ), // (S059) : (HID(USBCode)"KEY_SPACE");
	/* 122 */ Define_TM( 59, 87 ), // (S060) : (HID(USBCode)"KEY_MENU");
	/* 123 */ Define_TM( 59, 95 ), // (S060) : (HID(USBCode)"KEY_RGUI");
	/* 124 */ Define_TM( 60, 98 ), // (S061) : (layerShift(1));
	/* 125 */ Define_TM( 60, 100 ), // (S061) : (layerShift(3));
	/* 126 */ Define_TM( 61, 86 ), // (S062) : (HID(USBCode)"KEY_APP");
	/* 127 */ Define_TM( 61, 100 ), // (S062) : (layerShift(3));
	/* 128 */ Define_TM( 61, 94 ), // (S062) : (HID(USBCode)"KEY_RALT");
	/* 129 */ Define_TM( 62, 92 ), // (S063) : (HID(USBCode)"KEY_RCTRL");
	/* 130 */ Define_TM( 62, 101 ), // (S063) : (layerShift(4));
};


// -- Trigger Macro Record List

// Keeps a record/state of each trigger macro
TriggerMacroRecord TriggerMacroRecordList[ TriggerMacroNum ];



// ----- Trigger Maps -----

// MaxScanCode
// - This is retrieved from the KLL configuration
// - Should be corollated with the max scan code in the scan module
// - Maximum value is 0x100 (0x0 to 0xFF)
// - Increasing it beyond the keyboard's capabilities is just a waste of ram...
#define MaxScanCode 0x3F

// -- Trigger Lists
//
// Index 0: # of triggers in list
// Index n: pointer to trigger macro - use tm() macro

// - Default Layer -
Define_TL( default, 0x00 ) = { 0 };
Define_TL( default, 0x01 ) = { 1, 1 };
Define_TL( default, 0x02 ) = { 1, 2 };
Define_TL( default, 0x03 ) = { 1, 4 };
Define_TL( default, 0x04 ) = { 1, 6 };
Define_TL( default, 0x05 ) = { 1, 8 };
Define_TL( default, 0x06 ) = { 1, 10 };
Define_TL( default, 0x07 ) = { 1, 13 };
Define_TL( default, 0x08 ) = { 1, 15 };
Define_TL( default, 0x09 ) = { 1, 16 };
Define_TL( default, 0x0A ) = { 1, 19 };
Define_TL( default, 0x0B ) = { 1, 21 };
Define_TL( default, 0x0C ) = { 1, 23 };
Define_TL( default, 0x0D ) = { 1, 25 };
Define_TL( default, 0x0E ) = { 1, 27 };
Define_TL( default, 0x0F ) = { 1, 29 };
Define_TL( default, 0x10 ) = { 1, 31 };
Define_TL( default, 0x11 ) = { 1, 32 };
Define_TL( default, 0x12 ) = { 1, 36 };
Define_TL( default, 0x13 ) = { 1, 41 };
Define_TL( default, 0x14 ) = { 1, 42 };
Define_TL( default, 0x15 ) = { 1, 45 };
Define_TL( default, 0x16 ) = { 1, 46 };
Define_TL( default, 0x17 ) = { 1, 47 };
Define_TL( default, 0x18 ) = { 1, 49 };
Define_TL( default, 0x19 ) = { 1, 51 };
Define_TL( default, 0x1A ) = { 1, 53 };
Define_TL( default, 0x1B ) = { 1, 55 };
Define_TL( default, 0x1C ) = { 1, 56 };
Define_TL( default, 0x1D ) = { 1, 58 };
Define_TL( default, 0x1E ) = { 1, 60 };
Define_TL( default, 0x1F ) = { 1, 62 };
Define_TL( default, 0x20 ) = { 1, 67 };
Define_TL( default, 0x21 ) = { 1, 70 };
Define_TL( default, 0x22 ) = { 1, 74 };
Define_TL( default, 0x23 ) = { 1, 77 };
Define_TL( default, 0x24 ) = { 1, 78 };
Define_TL( default, 0x25 ) = { 1, 79 };
Define_TL( default, 0x26 ) = { 1, 81 };
Define_TL( default, 0x27 ) = { 1, 83 };
Define_TL( default, 0x28 ) = { 1, 86 };
Define_TL( default, 0x29 ) = { 1, 88 };
Define_TL( default, 0x2A ) = { 1, 89 };
Define_TL( default, 0x2B ) = { 1, 91 };
Define_TL( default, 0x2C ) = { 1, 92 };
Define_TL( default, 0x2D ) = { 1, 94 };
Define_TL( default, 0x2E ) = { 1, 97 };
Define_TL( default, 0x2F ) = { 1, 98 };
Define_TL( default, 0x30 ) = { 1, 100 };
Define_TL( default, 0x31 ) = { 1, 102 };
Define_TL( default, 0x32 ) = { 1, 105 };
Define_TL( default, 0x33 ) = { 1, 107 };
Define_TL( default, 0x34 ) = { 1, 109 };
Define_TL( default, 0x35 ) = { 1, 111 };
Define_TL( default, 0x36 ) = { 1, 112 };
Define_TL( default, 0x37 ) = { 1, 113 };
Define_TL( default, 0x38 ) = { 1, 117 };
Define_TL( default, 0x39 ) = { 1, 118 };
Define_TL( default, 0x3A ) = { 1, 119 };
Define_TL( default, 0x3B ) = { 1, 121 };
Define_TL( default, 0x3C ) = { 1, 123 };
Define_TL( default, 0x3D ) = { 1, 124 };
Define_TL( default, 0x3E ) = { 1, 128 };
Define_TL( default, 0x3F ) = { 1, 129 };


// - Partial Layers -
// Partial Layer 1
Define_TL( layer1, 0x00 ) = { 1, 0 };
Define_TL( layer1, 0x01 ) = { 1, 3 };
Define_TL( layer1, 0x02 ) = { 1, 5 };
Define_TL( layer1, 0x03 ) = { 1, 7 };
Define_TL( layer1, 0x04 ) = { 1, 9 };
Define_TL( layer1, 0x05 ) = { 1, 11 };
Define_TL( layer1, 0x06 ) = { 1, 12 };
Define_TL( layer1, 0x07 ) = { 1, 14 };
Define_TL( layer1, 0x08 ) = { 1, 17 };
Define_TL( layer1, 0x09 ) = { 1, 18 };
Define_TL( layer1, 0x0A ) = { 1, 20 };
Define_TL( layer1, 0x0B ) = { 1, 22 };
Define_TL( layer1, 0x0C ) = { 1, 24 };
Define_TL( layer1, 0x0D ) = { 1, 26 };
Define_TL( layer1, 0x0E ) = { 1, 28 };
Define_TL( layer1, 0x0F ) = { 1, 30 };
Define_TL( layer1, 0x10 ) = { 1, 34 };
Define_TL( layer1, 0x11 ) = { 1, 37 };
Define_TL( layer1, 0x12 ) = { 1, 39 };
Define_TL( layer1, 0x13 ) = { 1, 44 };
Define_TL( layer1, 0x14 ) = { 0 };
Define_TL( layer1, 0x15 ) = { 0 };
Define_TL( layer1, 0x16 ) = { 0 };
Define_TL( layer1, 0x17 ) = { 1, 48 };
Define_TL( layer1, 0x18 ) = { 1, 50 };
Define_TL( layer1, 0x19 ) = { 1, 52 };
Define_TL( layer1, 0x1A ) = { 1, 54 };
Define_TL( layer1, 0x1B ) = { 1, 57 };
Define_TL( layer1, 0x1C ) = { 1, 59 };
Define_TL( layer1, 0x1D ) = { 0 };
Define_TL( layer1, 0x1E ) = { 1, 64 };
Define_TL( layer1, 0x1F ) = { 1, 66 };
Define_TL( layer1, 0x20 ) = { 1, 72 };
Define_TL( layer1, 0x21 ) = { 1, 76 };
Define_TL( layer1, 0x22 ) = { 0 };
Define_TL( layer1, 0x23 ) = { 0 };
Define_TL( layer1, 0x24 ) = { 1, 80 };
Define_TL( layer1, 0x25 ) = { 1, 82 };
Define_TL( layer1, 0x26 ) = { 1, 84 };
Define_TL( layer1, 0x27 ) = { 1, 85 };
Define_TL( layer1, 0x28 ) = { 1, 87 };
Define_TL( layer1, 0x29 ) = { 0 };
Define_TL( layer1, 0x2A ) = { 1, 90 };
Define_TL( layer1, 0x2B ) = { 1, 93 };
Define_TL( layer1, 0x2C ) = { 1, 95 };
Define_TL( layer1, 0x2D ) = { 1, 96 };
Define_TL( layer1, 0x2E ) = { 1, 99 };
Define_TL( layer1, 0x2F ) = { 1, 101 };
Define_TL( layer1, 0x30 ) = { 1, 103 };
Define_TL( layer1, 0x31 ) = { 1, 104 };
Define_TL( layer1, 0x32 ) = { 1, 106 };
Define_TL( layer1, 0x33 ) = { 1, 108 };
Define_TL( layer1, 0x34 ) = { 1, 110 };
Define_TL( layer1, 0x35 ) = { 0 };
Define_TL( layer1, 0x36 ) = { 1, 115 };
Define_TL( layer1, 0x37 ) = { 1, 117 };
Define_TL( layer1, 0x38 ) = { 0 };
Define_TL( layer1, 0x39 ) = { 0 };
Define_TL( layer1, 0x3A ) = { 1, 120 };
Define_TL( layer1, 0x3B ) = { 1, 122 };
Define_TL( layer1, 0x3C ) = { 0 };
Define_TL( layer1, 0x3D ) = { 1, 126 };
Define_TL( layer1, 0x3E ) = { 1, 130 };

// Partial Layer 2
Define_TL( layer2, 0x00 ) = { 1, 38 };
Define_TL( layer2, 0x01 ) = { 0 };
Define_TL( layer2, 0x02 ) = { 0 };
Define_TL( layer2, 0x03 ) = { 0 };
Define_TL( layer2, 0x04 ) = { 0 };
Define_TL( layer2, 0x05 ) = { 0 };
Define_TL( layer2, 0x06 ) = { 0 };
Define_TL( layer2, 0x07 ) = { 0 };
Define_TL( layer2, 0x08 ) = { 0 };
Define_TL( layer2, 0x09 ) = { 0 };
Define_TL( layer2, 0x0A ) = { 0 };
Define_TL( layer2, 0x0B ) = { 0 };
Define_TL( layer2, 0x0C ) = { 1, 61 };
Define_TL( layer2, 0x0D ) = { 1, 63 };
Define_TL( layer2, 0x0E ) = { 1, 69 };
Define_TL( layer2, 0x0F ) = { 1, 73 };
Define_TL( layer2, 0x10 ) = { 0 };
Define_TL( layer2, 0x11 ) = { 0 };
Define_TL( layer2, 0x12 ) = { 0 };
Define_TL( layer2, 0x13 ) = { 0 };
Define_TL( layer2, 0x14 ) = { 0 };
Define_TL( layer2, 0x15 ) = { 0 };
Define_TL( layer2, 0x16 ) = { 0 };
Define_TL( layer2, 0x17 ) = { 0 };
Define_TL( layer2, 0x18 ) = { 0 };
Define_TL( layer2, 0x19 ) = { 0 };
Define_TL( layer2, 0x1A ) = { 0 };
Define_TL( layer2, 0x1B ) = { 0 };
Define_TL( layer2, 0x1C ) = { 0 };
Define_TL( layer2, 0x1D ) = { 0 };
Define_TL( layer2, 0x1E ) = { 0 };
Define_TL( layer2, 0x1F ) = { 0 };
Define_TL( layer2, 0x20 ) = { 0 };
Define_TL( layer2, 0x21 ) = { 0 };
Define_TL( layer2, 0x22 ) = { 0 };
Define_TL( layer2, 0x23 ) = { 0 };
Define_TL( layer2, 0x24 ) = { 0 };
Define_TL( layer2, 0x25 ) = { 1, 114 };
Define_TL( layer2, 0x26 ) = { 1, 116 };
Define_TL( layer2, 0x27 ) = { 0 };
Define_TL( layer2, 0x28 ) = { 0 };
Define_TL( layer2, 0x29 ) = { 0 };
Define_TL( layer2, 0x2A ) = { 1, 122 };
Define_TL( layer2, 0x2B ) = { 1, 125 };
Define_TL( layer2, 0x2C ) = { 1, 126 };
Define_TL( layer2, 0x2D ) = { 1, 130 };

// Partial Layer 3
Define_TL( layer3, 0x00 ) = { 1, 3 };
Define_TL( layer3, 0x01 ) = { 1, 5 };
Define_TL( layer3, 0x02 ) = { 1, 7 };
Define_TL( layer3, 0x03 ) = { 1, 9 };
Define_TL( layer3, 0x04 ) = { 0 };
Define_TL( layer3, 0x05 ) = { 0 };
Define_TL( layer3, 0x06 ) = { 0 };
Define_TL( layer3, 0x07 ) = { 0 };
Define_TL( layer3, 0x08 ) = { 0 };
Define_TL( layer3, 0x09 ) = { 0 };
Define_TL( layer3, 0x0A ) = { 0 };
Define_TL( layer3, 0x0B ) = { 0 };
Define_TL( layer3, 0x0C ) = { 0 };
Define_TL( layer3, 0x0D ) = { 0 };
Define_TL( layer3, 0x0E ) = { 0 };
Define_TL( layer3, 0x0F ) = { 1, 33 };
Define_TL( layer3, 0x10 ) = { 1, 35 };
Define_TL( layer3, 0x11 ) = { 1, 40 };
Define_TL( layer3, 0x12 ) = { 1, 43 };
Define_TL( layer3, 0x13 ) = { 0 };
Define_TL( layer3, 0x14 ) = { 0 };
Define_TL( layer3, 0x15 ) = { 0 };
Define_TL( layer3, 0x16 ) = { 0 };
Define_TL( layer3, 0x17 ) = { 0 };
Define_TL( layer3, 0x18 ) = { 0 };
Define_TL( layer3, 0x19 ) = { 0 };
Define_TL( layer3, 0x1A ) = { 0 };
Define_TL( layer3, 0x1B ) = { 0 };
Define_TL( layer3, 0x1C ) = { 0 };
Define_TL( layer3, 0x1D ) = { 1, 65 };
Define_TL( layer3, 0x1E ) = { 1, 68 };
Define_TL( layer3, 0x1F ) = { 1, 71 };
Define_TL( layer3, 0x20 ) = { 1, 75 };
Define_TL( layer3, 0x21 ) = { 0 };
Define_TL( layer3, 0x22 ) = { 0 };
Define_TL( layer3, 0x23 ) = { 0 };
Define_TL( layer3, 0x24 ) = { 0 };
Define_TL( layer3, 0x25 ) = { 0 };
Define_TL( layer3, 0x26 ) = { 0 };
Define_TL( layer3, 0x27 ) = { 0 };
Define_TL( layer3, 0x28 ) = { 0 };
Define_TL( layer3, 0x29 ) = { 0 };
Define_TL( layer3, 0x2A ) = { 0 };
Define_TL( layer3, 0x2B ) = { 0 };
Define_TL( layer3, 0x2C ) = { 0 };
Define_TL( layer3, 0x2D ) = { 0 };
Define_TL( layer3, 0x2E ) = { 0 };
Define_TL( layer3, 0x2F ) = { 0 };
Define_TL( layer3, 0x30 ) = { 0 };
Define_TL( layer3, 0x31 ) = { 0 };
Define_TL( layer3, 0x32 ) = { 0 };
Define_TL( layer3, 0x33 ) = { 0 };
Define_TL( layer3, 0x34 ) = { 0 };
Define_TL( layer3, 0x35 ) = { 1, 114 };
Define_TL( layer3, 0x36 ) = { 1, 116 };
Define_TL( layer3, 0x37 ) = { 0 };
Define_TL( layer3, 0x38 ) = { 0 };
Define_TL( layer3, 0x39 ) = { 0 };
Define_TL( layer3, 0x3A ) = { 0 };
Define_TL( layer3, 0x3B ) = { 0 };
Define_TL( layer3, 0x3C ) = { 1, 127 };
Define_TL( layer3, 0x3D ) = { 1, 130 };


// -- ScanCode Offset Map
// Maps interconnect ids to scancode offsets
//
// Only used for keyboards with an interconnect
const uint8_t InterconnectOffsetList[] = {
	0x00,
	0x3F,
};


// -- ScanCode Indexed Maps
// Maps to a trigger list of macro pointers
//                 _
// <scan code> -> |T|
//                |r| -> <trigger macro pointer 1>
//                |i|
//                |g| -> <trigger macro pointer 2>
//                |g|
//                |e| -> <trigger macro pointer 3>
//                |r|
//                |s| -> <trigger macro pointer n>
//                 -

// - Default Map for ScanCode Lookup -
const nat_ptr_t *default_scanMap[] = { 
default_tl_0x00, default_tl_0x01, default_tl_0x02, default_tl_0x03, default_tl_0x04, default_tl_0x05, default_tl_0x06, default_tl_0x07, default_tl_0x08, default_tl_0x09, default_tl_0x0A, default_tl_0x0B, default_tl_0x0C, default_tl_0x0D, default_tl_0x0E, default_tl_0x0F, default_tl_0x10, default_tl_0x11, default_tl_0x12, default_tl_0x13, default_tl_0x14, default_tl_0x15, default_tl_0x16, default_tl_0x17, default_tl_0x18, default_tl_0x19, default_tl_0x1A, default_tl_0x1B, default_tl_0x1C, default_tl_0x1D, default_tl_0x1E, default_tl_0x1F, default_tl_0x20, default_tl_0x21, default_tl_0x22, default_tl_0x23, default_tl_0x24, default_tl_0x25, default_tl_0x26, default_tl_0x27, default_tl_0x28, default_tl_0x29, default_tl_0x2A, default_tl_0x2B, default_tl_0x2C, default_tl_0x2D, default_tl_0x2E, default_tl_0x2F, default_tl_0x30, default_tl_0x31, default_tl_0x32, default_tl_0x33, default_tl_0x34, default_tl_0x35, default_tl_0x36, default_tl_0x37, default_tl_0x38, default_tl_0x39, default_tl_0x3A, default_tl_0x3B, default_tl_0x3C, default_tl_0x3D, default_tl_0x3E, default_tl_0x3F
};


// - Partial Layer ScanCode Lookup Maps -
// Partial Layer 1
const nat_ptr_t *layer1_scanMap[] = { 
layer1_tl_0x00, layer1_tl_0x01, layer1_tl_0x02, layer1_tl_0x03, layer1_tl_0x04, layer1_tl_0x05, layer1_tl_0x06, layer1_tl_0x07, layer1_tl_0x08, layer1_tl_0x09, layer1_tl_0x0A, layer1_tl_0x0B, layer1_tl_0x0C, layer1_tl_0x0D, layer1_tl_0x0E, layer1_tl_0x0F, layer1_tl_0x10, layer1_tl_0x11, layer1_tl_0x12, layer1_tl_0x13, layer1_tl_0x14, layer1_tl_0x15, layer1_tl_0x16, layer1_tl_0x17, layer1_tl_0x18, layer1_tl_0x19, layer1_tl_0x1A, layer1_tl_0x1B, layer1_tl_0x1C, layer1_tl_0x1D, layer1_tl_0x1E, layer1_tl_0x1F, layer1_tl_0x20, layer1_tl_0x21, layer1_tl_0x22, layer1_tl_0x23, layer1_tl_0x24, layer1_tl_0x25, layer1_tl_0x26, layer1_tl_0x27, layer1_tl_0x28, layer1_tl_0x29, layer1_tl_0x2A, layer1_tl_0x2B, layer1_tl_0x2C, layer1_tl_0x2D, layer1_tl_0x2E, layer1_tl_0x2F, layer1_tl_0x30, layer1_tl_0x31, layer1_tl_0x32, layer1_tl_0x33, layer1_tl_0x34, layer1_tl_0x35, layer1_tl_0x36, layer1_tl_0x37, layer1_tl_0x38, layer1_tl_0x39, layer1_tl_0x3A, layer1_tl_0x3B, layer1_tl_0x3C, layer1_tl_0x3D, layer1_tl_0x3E
};

// Partial Layer 2
const nat_ptr_t *layer2_scanMap[] = { 
layer2_tl_0x00, layer2_tl_0x01, layer2_tl_0x02, layer2_tl_0x03, layer2_tl_0x04, layer2_tl_0x05, layer2_tl_0x06, layer2_tl_0x07, layer2_tl_0x08, layer2_tl_0x09, layer2_tl_0x0A, layer2_tl_0x0B, layer2_tl_0x0C, layer2_tl_0x0D, layer2_tl_0x0E, layer2_tl_0x0F, layer2_tl_0x10, layer2_tl_0x11, layer2_tl_0x12, layer2_tl_0x13, layer2_tl_0x14, layer2_tl_0x15, layer2_tl_0x16, layer2_tl_0x17, layer2_tl_0x18, layer2_tl_0x19, layer2_tl_0x1A, layer2_tl_0x1B, layer2_tl_0x1C, layer2_tl_0x1D, layer2_tl_0x1E, layer2_tl_0x1F, layer2_tl_0x20, layer2_tl_0x21, layer2_tl_0x22, layer2_tl_0x23, layer2_tl_0x24, layer2_tl_0x25, layer2_tl_0x26, layer2_tl_0x27, layer2_tl_0x28, layer2_tl_0x29, layer2_tl_0x2A, layer2_tl_0x2B, layer2_tl_0x2C, layer2_tl_0x2D
};

// Partial Layer 3
const nat_ptr_t *layer3_scanMap[] = { 
layer3_tl_0x00, layer3_tl_0x01, layer3_tl_0x02, layer3_tl_0x03, layer3_tl_0x04, layer3_tl_0x05, layer3_tl_0x06, layer3_tl_0x07, layer3_tl_0x08, layer3_tl_0x09, layer3_tl_0x0A, layer3_tl_0x0B, layer3_tl_0x0C, layer3_tl_0x0D, layer3_tl_0x0E, layer3_tl_0x0F, layer3_tl_0x10, layer3_tl_0x11, layer3_tl_0x12, layer3_tl_0x13, layer3_tl_0x14, layer3_tl_0x15, layer3_tl_0x16, layer3_tl_0x17, layer3_tl_0x18, layer3_tl_0x19, layer3_tl_0x1A, layer3_tl_0x1B, layer3_tl_0x1C, layer3_tl_0x1D, layer3_tl_0x1E, layer3_tl_0x1F, layer3_tl_0x20, layer3_tl_0x21, layer3_tl_0x22, layer3_tl_0x23, layer3_tl_0x24, layer3_tl_0x25, layer3_tl_0x26, layer3_tl_0x27, layer3_tl_0x28, layer3_tl_0x29, layer3_tl_0x2A, layer3_tl_0x2B, layer3_tl_0x2C, layer3_tl_0x2D, layer3_tl_0x2E, layer3_tl_0x2F, layer3_tl_0x30, layer3_tl_0x31, layer3_tl_0x32, layer3_tl_0x33, layer3_tl_0x34, layer3_tl_0x35, layer3_tl_0x36, layer3_tl_0x37, layer3_tl_0x38, layer3_tl_0x39, layer3_tl_0x3A, layer3_tl_0x3B, layer3_tl_0x3C, layer3_tl_0x3D
};



// ----- Layer Index -----

// -- Layer Index List
//
// Index 0: Default map
// Index n: Additional layers
const Layer LayerIndex[] = {
	Layer_IN( default_scanMap, "D: _srv_KiiConf_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PartialMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PixelMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_HID-IO@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_USB@['capabilities']_processed.kll + _srv_KiiConf_controller_Debug_latency@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map', 'standard']_processed.kll + _srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll + @['MD1', '1-Standard-0']_processed.kll", 0x00 ),
	Layer_IN( layer1_scanMap, "1: _srv_KiiConf_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PartialMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PixelMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_HID-IO@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_USB@['capabilities']_processed.kll + _srv_KiiConf_controller_Debug_latency@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map', 'standard']_processed.kll + _srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll + @['MD1', '1-Standard-1']_processed.kll", 0x01 ),
	Layer_IN( layer2_scanMap, "2: _srv_KiiConf_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PartialMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PixelMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_HID-IO@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_USB@['capabilities']_processed.kll + _srv_KiiConf_controller_Debug_latency@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map', 'standard']_processed.kll + _srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll + @['MD1', '1-Standard-2']_processed.kll", 0x12 ),
	Layer_IN( layer3_scanMap, "3: _srv_KiiConf_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PartialMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Macro_PixelMap@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_HID-IO@['capabilities']_processed.kll + _srv_KiiConf_controller_Output_USB@['capabilities']_processed.kll + _srv_KiiConf_controller_Debug_latency@['capabilities']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map']_processed.kll + _srv_KiiConf_controller_Scan_Infinity_60_LED@['scancode_map', 'standard']_processed.kll + _srv_KiiConf_controller_kll_layouts@['stdFuncMap']_processed.kll + @['MD1', '1-Standard-3']_processed.kll", 0x02 ),
};


// - Layer State
LayerStateType LayerState[ LayerNum ];



// ----- Key Positions -----

// -- Physical Key Positions
//
// Index 0: Key 1
// Each key has 6 dimensions
// x,y,z and rx,ry,rz (rotation)
// Units are in mm
const Position Key_Positions[] = {
	PositionEntry( 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S001 <= x:0,y:0;
	PositionEntry( 19.05, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S002 <= x:19.05,y:0;
	PositionEntry( 38.1, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S003 <= x:38.1,y:0;
	PositionEntry( 57.15, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S004 <= x:57.15,y:0;
	PositionEntry( 76.2, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S005 <= x:76.2,y:0;
	PositionEntry( 95.25, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S006 <= x:95.25,y:0;
	PositionEntry( 114.3, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S007 <= x:114.3,y:0;
	PositionEntry( 133.35, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S008 <= x:133.35,y:0;
	PositionEntry( 152.4, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S009 <= x:152.4,y:0;
	PositionEntry( 171.45, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S010 <= x:171.45,y:0;
	PositionEntry( 190.5, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S011 <= x:190.5,y:0;
	PositionEntry( 209.55, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S012 <= x:209.55,y:0;
	PositionEntry( 228.6, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S013 <= x:228.6,y:0;
	PositionEntry( 247.65, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S014 <= x:247.65,y:0;
	PositionEntry( 266.7, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S015 <= x:266.7,y:0;
	PositionEntry( 4.76, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S016 <= x:4.76,y:-19.05;
	PositionEntry( 27.81, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S017 <= x:27.81,y:-19.05;
	PositionEntry( 46.86, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S018 <= x:46.86,y:-19.05;
	PositionEntry( 65.91, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S019 <= x:65.91,y:-19.05;
	PositionEntry( 84.96, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S020 <= x:84.96,y:-19.05;
	PositionEntry( 104.01, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S021 <= x:104.01,y:-19.05;
	PositionEntry( 123.06, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S022 <= x:123.06,y:-19.05;
	PositionEntry( 142.11, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S023 <= x:142.11,y:-19.05;
	PositionEntry( 161.16, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S024 <= x:161.16,y:-19.05;
	PositionEntry( 180.21, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S025 <= x:180.21,y:-19.05;
	PositionEntry( 199.26, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S026 <= x:199.26,y:-19.05;
	PositionEntry( 218.31, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S027 <= x:218.31,y:-19.05;
	PositionEntry( 237.36, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S028 <= x:237.36,y:-19.05;
	PositionEntry( 260.41, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S029 <= x:260.41,y:-19.05;
	PositionEntry( 7.14, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S030 <= x:7.14,y:-38.10;
	PositionEntry( 33.14, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S031 <= x:33.14,y:-38.10;
	PositionEntry( 52.19, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S032 <= x:52.19,y:-38.10;
	PositionEntry( 71.24, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S033 <= x:71.24,y:-38.10;
	PositionEntry( 90.29, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S034 <= x:90.29,y:-38.10;
	PositionEntry( 109.34, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S035 <= x:109.34,y:-38.10;
	PositionEntry( 128.39, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S036 <= x:128.39,y:-38.10;
	PositionEntry( 147.44, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S037 <= x:147.44,y:-38.10;
	PositionEntry( 166.49, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S038 <= x:166.49,y:-38.10;
	PositionEntry( 185.54, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S039 <= x:185.54,y:-38.10;
	PositionEntry( 204.59, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S040 <= x:204.59,y:-38.10;
	PositionEntry( 223.64, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S041 <= x:223.64,y:-38.10;
	PositionEntry( 254.64, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S042 <= x:254.64,y:-38.10;
	PositionEntry( 11.9, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S043 <= x:11.9,y:-57.15;
	PositionEntry( 42.9, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S044 <= x:42.9,y:-57.15;
	PositionEntry( 61.95, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S045 <= x:61.95,y:-57.15;
	PositionEntry( 81.0, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S046 <= x:81,y:-57.15;
	PositionEntry( 100.05, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S047 <= x:100.05,y:-57.15;
	PositionEntry( 119.1, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S048 <= x:119.1,y:-57.15;
	PositionEntry( 138.15, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S049 <= x:138.15,y:-57.15;
	PositionEntry( 157.2, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S050 <= x:157.2,y:-57.15;
	PositionEntry( 176.25, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S051 <= x:176.25,y:-57.15;
	PositionEntry( 195.3, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S052 <= x:195.3,y:-57.15;
	PositionEntry( 214.35, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S053 <= x:214.35,y:-57.15;
	PositionEntry( 240.35, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S054 <= x:240.35,y:-57.15;
	PositionEntry( 266.7, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S055 <= x:266.7,y:-57.15;
	PositionEntry( 2.381, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S056 <= x:2.381,y:-76.20;
	PositionEntry( 26.193, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S057 <= x:26.193,y:-76.20;
	PositionEntry( 50.006, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S058 <= x:50.006,y:-76.20;
	PositionEntry( 121.443, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S059 <= x:121.443,y:-76.20;
	PositionEntry( 195.262, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S060 <= x:195.262,y:-76.20;
	PositionEntry( 216.693, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S061 <= x:216.693,y:-76.20;
	PositionEntry( 240.493, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S062 <= x:240.493,y:-76.20;
	PositionEntry( 264.306, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S063 <= x:264.306,y:-76.20;
};

